### ISSUE TITLE
How to set column width

### ISSUE THREAD

**Issue by wwdok** [midzer/FilterTable#1]
Hello @midzer , When i was seaching filter and QT, i found this repo, it is helpful to reference. Now i encountered a problem, i know this repo has been uploaded for 4 years, if you could give me some tips, that would be very nice, my problem is i want to resize the width of each column, so i add follwing code(for simplicity, i just set the first column) :
![image](https://user-images.githubusercontent.com/43233772/115999876-47e0a100-a620-11eb-9d86-693d2e740d1e.png)
But neither method works...How to solve this problem ?
Thank you in advance !

**Comment by midzer** [comment]
Hi @wwdok thanks for your issue.

I'm not to familiar with Qt any more. But I found this at stackoverflow https://stackoverflow.com/questions/26681578/qtableview-column-width

**Comment by wwdok** [comment]
Your reply is so quick, hahaha, i just make it Ok ! I saw that answer too, so i placed those two lines after setModel(), but here it is not enought, it should be placed  after `view->setHorizontalHeader(header);` :
![image](https://user-images.githubusercontent.com/43233772/116000404-9f800c00-a622-11eb-8d6c-5e83ce0321ee.png)
![image](https://user-images.githubusercontent.com/43233772/116000414-a9a20a80-a622-11eb-8615-c5fc9271b7d1.png)
Sorry to bother you, Thank you again !

**Comment by midzer** [comment]
No worries, have a nice day!
